/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View, TouchableOpacity} from 'react-native';
import {
  startDLNAService,
  stopDLNAService,
  onDlnaMediaInfo,
  onDlnaStateChange,
} from 'react-native-dlna';

export default class App extends Component {
  start = () => {
    startDLNAService('秃尾巴的猫');
  };

  stop = () => {
    stopDLNAService();
  };

  componentDidMount() {
    onDlnaMediaInfo(data => {
      console.log(' >> onDlnaMediaInfo:', data);
    });
    onDlnaStateChange(data => {
      console.log(' >> onDlnaStateChange:', data);
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆react-native-dlna☆</Text>
        <TouchableOpacity style={styles.start} onPress={this.start}>
          <Text style={styles.text}>RNDLNA START</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.stop} onPress={this.stop}>
          <Text style={styles.text}>RNDLNA STOP</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  start: {
    width: 180,
    backgroundColor: '#7655FD',
    height: 44,
    borderRadius: 12,
    marginTop: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stop: {
    width: 180,
    backgroundColor: '#FF3030',
    height: 44,
    borderRadius: 12,
    marginTop: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    color: '#fff',
  },
});
